config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { registrations: "customers/registrations" }

  root 'welcome#index'

  get "account" => "account#index"
  get "dashboard/customers" => "dashboard#customers"
  get "dashboard" => "dashboard#index"
  get "dashboard/:date" => "dashboard#dashboard", as: :date_dashboard

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders

  scope :unique_in_month, -> (month) {
    joins(:orders).where("orders.created_at": month).uniq
  }
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :product_items
  has_many :products, through: :product_items
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
  belongs_to :customer
  has_many :items, through: :product

  scope :from_week_starting_on, -> (start_date) { where(created_at: start_date..(start_date + 7.days))}

  scope :sold_count_for_week_starting_on, -> (start_date) {
    joins(:product)
      .from_week_starting_on(start_date)
      .group(:product)
      .count
  }

  scope :by_customer, -> (start_date) {
    joins(:customer)
      .from_week_starting_on(start_date)
      .group(:customer_id)
      .count
  }

  def self.items_sold_count(start_date)
    sold_count = includes(:items)
      .from_week_starting_on(start_date)
      .map(&:items)
      .flatten
      .group_by { |item| item.id }
      .map { |k, v| [k, v.size] }
      .to_h

    items = Item.find(sold_count.keys)

    items.map { |item| [item, sold_count[item.id]] }.to_h
  end

  def self.orders_count_by_customer_for_week_starting_on(start_date)
    by_customer(start_date)
      .values
      .each
      .with_object(Hash.new(0)) do |order_count, counts|
        counts[order_count] += 1
      end
  end

  enum status: [:draft, :confirmed, :canceled]
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :product_items
  has_many :items, through: :product_items
  belongs_to :category
end

app/models/product_item.rb
class ProductItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :product
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  before_action :authenticate_customer!

  def index
    @orders = current_customer.orders.order(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers/registrations_controller.rb
class Customers::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do |customer|
      generate_fake_orders(customer)
    end
  end

  def generate_fake_orders(customer)
    return unless customer.persisted?

    product_ids = Product.pluck(:id)

    5.times do
      timestamp = Faker::Time.between(2.weeks.ago, DateTime.now)
      customer.orders.create!(
        product_id: product_ids.sample,
        status: Order.statuses.values.sample,
        created_at: timestamp,
        updated_at: timestamp)
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_customer!

  def index
    redirect_to date_dashboard_path(Date.today - 6.days)
  end

  def dashboard
    @day = Date.parse(params[:date])
    @products_sold_count = Order.sold_count_for_week_starting_on(@day)

    @items_sold_count = Order.items_sold_count(@day)

    @orders_count = Order.orders_count_by_customer_for_week_starting_on(@day)
    @total_orders = @orders_count.values.sum

    # 5. (*On a separate view*) Display repartition between reccuring and new customers for each month (example 2)
  end

  def customers

    # build list of month ranges to get orders for that month
    oldest_order_date = Date.parse(Order.order(:created_at).first.created_at.to_s)
    order_date = oldest_order_date.dup
    today = Date.today
    month_ranges = []

    while order_date < today do
      month_ranges << order_date.all_month
      order_date = order_date.next_month
    end

    # get customers who ordered each month
    @customers_by_month = month_ranges.map do |month|
      [month.first.strftime("%B %Y"), Customer.unique_in_month(month).to_a]
    end

    old_customers = []

    @new_and_old_customers = @customers_by_month.map { |month_name, this_month_customers|
      # new customers are any customers seen this month who haven't been seen in previous months
      # i.e. they are not in the old customers list yet
      new_customers = this_month_customers - old_customers

      # repeat customers are customers from this month who are already in the old customers list,
      # e.g. the intersection of the two lists
      repeat_customers = this_month_customers & old_customers

      # all new and old customers from this month get added to old_customers for next month
      # with duplicates removed
      old_customers |= this_month_customers


      [month_name, repeat_customers.size, new_customers.size, this_month_customers.size]
    }
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/customers.html.erb
<h2>Customers</h2>


<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th>Month</th>
      <th>Recurring Customers</th>
      <th>New Customers</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @new_and_old_customers.each do |month_name, new_customer_count, repeat_customer_count, total_customer_count| %>
      <tr>
        <td><%= month_name %></td>
        <td><%= new_customer_count %></td>
        <td><%= repeat_customer_count %></td>
        <td><%= total_customer_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/dashboard.html.erb
<h2>Sales Summary For the Week of
<%= @day %> to <%= @day + 6.days %>
</h2>

<%= link_to date_dashboard_path(@day - 1.week) do %>
  <%= fa_icon "chevron-left" %> Previous Week
<% end %>
|
<%= link_to "Current Week", dashboard_path %>
|
<%= link_to date_dashboard_path(@day + 1.week) do %>
   Next Week <%= fa_icon "chevron-right" %>
<% end %>

<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="tab" href="#products-sold" role="tab">Products Sold</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#items-sold" role="tab">Items Sold</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#customer-order-volume" role="tab">Customer Order Volume</a>
  </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div class="tab-pane active" id="products-sold" role="tabpanel">
    <table class="table table-striped">
      <thead class="thead-inverse">
        <tr>
          <th>Product Id</th>
          <th>Product Name</th>
          <th>Quantity Sold</th>
        </tr>
      </thead>
      <tbody>
        <% @products_sold_count.each do |product, quantity_sold| %>
          <tr>
            <td><%= product.id %></td>
            <td><%= product.name %></td>
            <td><%= quantity_sold %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="tab-pane" id="items-sold" role="tabpanel">
    <table class="table table-striped">
      <thead class="thead-inverse">
        <tr>
          <th>Item Id</th>
          <th>Item Name</th>
          <th>Quantity Sold</th>
        </tr>
      </thead>
      <tbody>
        <% @items_sold_count.each do |item, count| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= item.name %></td>
            <td><%= count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="tab-pane" id="customer-order-volume" role="tabpanel">
    <table class="table table-striped">
      <thead class="thead-inverse">
        <tr>
          <th># of Orders</th>
          <th># of Customers</th>
          <th>Percentage</th>
        </tr>
      </thead>
      <tbody>
        <% @orders_count.each do |order_count, customer_count| %>
          <tr>
            <td><%= pluralize(order_count, "order") %></td>
            <td><%= customer_count %></td>
            <td><%= number_to_percentage((customer_count.to_f / @total_orders) * 100, precision: 0) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboard/index.html.erb
<table>
  <thead>
    <tr>
      <th>Product Id</th>
      <th>Product Name</th>
      <th>Quantity Sold</th>
    </tr>
  </thead>
  <tbody>
    <% @products_sold_count.each do |product, quantity_sold| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= quantity_sold %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<table>
  <thead>
    <tr>
      <th>Item Id</th>
      <th>Item Name</th>
      <th>Quantity Sold</th>
    </tr>
  </thead>
  <tbody>
    <% @items_sold_count.each do |item, count| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.name %></td>
        <td><%= count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>RailsCodingTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/header" %>
  <div class="container">
    <%= render 'shared/messages' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-light bg-faded">
  <%= link_to "Flower Power", root_path, class: "navbar-brand" %>
  <ul class="nav navbar-nav">
    <li class="nav-item">
      <%= link_to "My Orders", account_path, class: "nav-link" %>
    </li>

    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="supportedContentDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dashboard</a>
      <div class="dropdown-menu" aria-labelledby="supportedContentDropdown">
        <%= link_to "Sales by week", dashboard_path, class: "dropdown-item" %>
        <%= link_to "Return customers", dashboard_customers_path, class: "dropdown-item" %>
      </div>
    </li>
  </ul>
  <ul class="nav navbar-nav float-xs-right">
    <% if customer_signed_in? %>
      <li class="nav-item">
      <%= link_to('Logout', destroy_customer_session_path, :method => :delete, class: "btn btn-outline-danger") %>
      </li>
    <% else %>
      <li class="nav-item">
      <%= link_to('Login', new_customer_session_path, class: "btn btn-outline-primary")  %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <%= value %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Flower Power!</h1>

<p>Please use the links above to discover your flower power</p>